#COMPONENT_PRIV_INCLUDEDIRS=. .. ${PROJECT_PATH}/src/GameState/Powerups ${PROJECT_PATH}/src/GameState/Playfields
COMPONENT_EXTRA_INCLUDES=${CREATIVE_ENGINE_PATH}/src
COMPONENT_EXTRA_INCLUDES+=${CREATIVE_ENGINE_PATH}/src/Widgets
COMPONENT_EXTRA_INCLUDES+=${PROJECT_PATH}/src
COMPONENT_EXTRA_INCLUDES+=${PROJECT_PATH}/src/GameState
COMPONENT_EXTRA_INCLUDES+=${PROJECT_PATH}/src/SplashState
COMPONENT_EXTRA_INCLUDES+=${PROJECT_PATH}/src/TitleState
